site_name: System Design Toolkit

nav:
  - Home: index.md
  - System Design:
      - Fundamentals: 01SystemDesign/Fundamentals.md
      - Pattern: 01SystemDesign/Pattern.md
      - Tips: 01SystemDesign/Tips.md
      - Key Technologies:
          - Redis: 01SystemDesign/KeyTechnologies/Redis.md
          - DynamoDb: DynamoDb.md
          - Cassandra: Cassandra.md
      - Core Concepts:
          - Network Fundamentals: 01SystemDesign/CoreConcepts/Network.md
          - Db Fundamentals: 01SystemDesign/CoreConcepts/Db.md
          - Caching: 01SystemDesign/CoreConcepts/Caching.md
          - API Design: 01SystemDesign/CoreConcepts/API.md
      - Advanced Concept:
          - Vector Db: 01SystemDesign/AdvancedConcept/Vector.md
          - Time Series Db: 01SystemDesign/AdvancedConcept/TimeSeriesDb.md

  - High-Level Design (HLD):
      - DropBox: 08HLDExample/DropBox.md
      - Youtube: 08HLDExample/Youtube.md
      - Strava: 08HLDExample/Strava.md
      - YoutubeTopK: 08HLDExample/YoutubeTopK.md

  - Low-Level Design (LLD):
      - Structural Pattern: 07LLDExample/StructuralPattern.md
      - Creational Pattern: 07LLDExample/CreationalPattern.md

  - Java:
      - Code Quiz: 02Java/03CodeSnippet.md
      - Interview Questions: 02Java/02InterviewQuestion.md
      - Interview Questions Part 1: 02Java/01InterviewQuestion.md
      - Java OOPs: 02Java/OOPs.md
      - Multithreading: 02Java/Multithreading.md
      - REST API: 02Java/ProjectRESTAPI.md
      - Sample: 02Java/Sample.md

  - Microservices:
      - Fundamentals: Microservices/Fundamentals.md
      - Communication: 03Microservice/01Communication.md
      - Data Management: Microservices/DataManagement.md
      - Resilience: Microservices/Resilience.md
      - Observability: Microservices/Observability.md

  - Spring Boot:
      - Fundamentals: 04Spring/InterviewQuestionBean.md
      - Layered Architecture: SpringBoot/LayeredArchitecture.md
      - Building Microservices: SpringBoot/BuildingMicroservices.md
      - Security: SpringBoot/Security.md
      - Testing: SpringBoot/Testing.md

  - KafkaFundamentals:
      - ProducerConsumer: KafkaFundamentals/ProducerConsumer.md
  - Quiz: Quiz.md
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.code.expand
    - content.code.mermaid
#    - toc.integrate
#    - header.autohide
extra_css:
  - css/custom.css
